repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.15
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
    rev: v0.12.11
    hooks:
        # Run the linter.
        - id: ruff-check
        # Run the formatter.
        - id: ruff-format
